language: elixir
elixir:
  - 1.2.6
  - 1.3.1
otp_release:
  - 18.2
addons:
  postgresql: "9.4"
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
install:
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
